language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --no-ansi --no-progress --optimize-autoloader

before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS homestead;" -uroot
  - mysql -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON homestead.* TO 'homestead'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot

script:
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate --seed --env=local
  - vendor/bin/phpunit
